/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_zafu_jnidemo_Test */

#ifndef _Included_cn_edu_zafu_jnidemo_Test
#define _Included_cn_edu_zafu_jnidemo_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_zafu_jnidemo_Test
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_edu_zafu_jnidemo_Test_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
